import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { MapPin, ShieldCheck } from "lucide-react";
import { RaktaLayout } from "@/components/RaktaLayout";
import { images } from "@/lib/rakta-data";
import type { Lang } from "@/lib/rakta-copy";

export const Route = createFileRoute("/profile")({ head: () => ({ meta: [{ title: "Donor Profile | Rakta-Seva Connect" }, { name: "description", content: "Privacy-safe donor profile with availability status." }, { property: "og:title", content: "Donor Profile" }, { property: "og:description", content: "View blood group and availability without exposing exact location." }] }), component: ProfilePage });
function ProfilePage() { const [lang,setLang]=useState<Lang>("en"); const [dark,setDark]=useState(true); return <RaktaLayout lang={lang} setLang={setLang} dark={dark} setDark={setDark}><section className="container-rakta grid place-items-center py-16"><article className="glass-panel w-full max-w-xl overflow-hidden rounded-3xl"><img src={images.handsImage} alt="Profile photo" width={1920} height={1080} className="h-72 w-full object-cover" /><div className="p-7"><p className="text-sm font-black text-primary">DONOR PROFILE</p><h1 className="mt-2 text-4xl font-black">A•••• Kumar</h1><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-secondary p-4"><p className="text-sm text-muted-foreground">Blood Group</p><p className="text-3xl font-black text-primary">O+</p></div><div className="rounded-2xl bg-secondary p-4"><p className="text-sm text-muted-foreground">Availability</p><p className="text-2xl font-black text-success">Available</p></div></div><p className="mt-5 flex items-center gap-2 text-muted-foreground"><MapPin size={18} /> Approximate area only: Patna Central</p><p className="mt-3 flex items-center gap-2 text-sm font-bold"><ShieldCheck size={18} className="text-success" /> Exact location and phone number hidden.</p></div></article></section></RaktaLayout>; }
