/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelfCheckRouteImport } from './routes/self-check'
import { Route as RequestRouteImport } from './routes/request'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SelfCheckRoute = SelfCheckRouteImport.update({
  id: '/self-check',
  path: '/self-check',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/donors': typeof DonorsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/self-check': typeof SelfCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/donors': typeof DonorsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/self-check': typeof SelfCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/donors': typeof DonorsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/request': typeof RequestRoute
  '/self-check': typeof SelfCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/donors'
    | '/profile'
    | '/register'
    | '/request'
    | '/self-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/donors'
    | '/profile'
    | '/register'
    | '/request'
    | '/self-check'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/donors'
    | '/profile'
    | '/register'
    | '/request'
    | '/self-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DonorsRoute: typeof DonorsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RequestRoute: typeof RequestRoute
  SelfCheckRoute: typeof SelfCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/self-check': {
      id: '/self-check'
      path: '/self-check'
      fullPath: '/self-check'
      preLoaderRoute: typeof SelfCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DonorsRoute: DonorsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RequestRoute: RequestRoute,
  SelfCheckRoute: SelfCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
